repos:
  - repo: https://github.com/psf/black
    rev: '24.3.0'
    hooks:
      - id: black
        language_version: python3 
        exclude: |
          ^(layeredrl/tdmpc2)/
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--extend-ignore=E203']
        exclude: |
          ^(layeredrl/tdmpc2)/
